<template>
  <RecycleScroller class="scroller" :items="list" :item-size="32" key-field="id" v-slot="{ item }">
    <SchemaItem :item="item" />
  </RecycleScroller>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import SchemaItem from './item/SchemaItem.vue'
import type Schema from '@/components/types/schema'

const schemaData: Schema = {
  title: 'Root Schema',
  type: 'object',
  properties: {
    name: { type: 'string' },
    age: { type: 'number' },
    address: {
      type: 'object',
      properties: {
        street: { type: 'string' },
        city: { type: 'string' },
      },
    },
  },
}

const list = ref([
  {
    id: 0,
    keyPath: [],
    title: 'Root Schema',
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      age: {
        type: 'number',
      },
      address: {
        type: 'object',
        properties: {
          street: {
            type: 'string',
          },
          city: {
            type: 'string',
          },
        },
      },
    },
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
  {
    id: 1,
    keyPath: ['name'],
    title: undefined,
    type: 'string',
    properties: undefined,
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
  {
    id: 2,
    keyPath: ['age'],
    title: undefined,
    type: 'number',
    properties: undefined,
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
  {
    id: 3,
    keyPath: ['address'],
    title: undefined,
    type: 'object',
    properties: {
      street: {
        type: 'string',
      },
      city: {
        type: 'string',
      },
    },
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
  {
    id: 4,
    keyPath: ['address', 'street'],
    title: undefined,
    type: 'string',
    properties: undefined,
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
  {
    id: 5,
    keyPath: ['address', 'city'],
    title: undefined,
    type: 'string',
    properties: undefined,
    required: undefined,
    description: undefined,
    default: undefined,
    mock: undefined,
    minLength: undefined,
    maxLength: undefined,
    minimum: undefined,
    maximum: undefined,
    pattern: undefined,
    enum: undefined,
    enumDesc: undefined,
    format: undefined,
    exclusiveMinimum: undefined,
    exclusiveMaximum: undefined,
    items: undefined,
    minItems: undefined,
    maxItems: undefined,
    uniqueItems: undefined,
  },
])
</script>

<style scoped></style>
